version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: asgiref
    versions:
    - 3.3.1
    - 3.3.2
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: django-crispy-forms
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.1
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: pytz
    versions:
    - "2020.5"
