# Generated by Django 3.1 on 2020-09-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblperfil',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tblperfil',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
