# Generated by Django 3.1 on 2020-09-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('links', '0003_auto_20200912_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblperfil',
            name='picture',
            field=models.ImageField(blank=True, default='users/picture/default-profile.png',
                                    upload_to='users/pictures'),
        ),
    ]
