# Generated by Django 3.1 on 2020-09-11 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAreaLaboral',
            fields=[
                ('id_area_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('area_laboral', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_area_laboral',
            },
        ),
        migrations.CreateModel(
            name='TblAuxiliar',
            fields=[
                ('id_auxiliar', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion_auxiliar', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'tbl_auxiliar',
            },
        ),
        migrations.CreateModel(
            name='TblCargoEmpleado',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_empleado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_cargo_empleado',
            },
        ),
        migrations.CreateModel(
            name='TblDisponibilidadAuxiliar',
            fields=[
                ('id_disponibilidad_auxiliar', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_disponibilidad_auxiliar',
            },
        ),
        migrations.CreateModel(
            name='TblEmpleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('id_area_laboral', models.ForeignKey(db_column='id_area_laboral', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblarealaboral')),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblcargoempleado')),
            ],
            options={
                'db_table': 'tbl_empleado',
            },
        ),
        migrations.CreateModel(
            name='TblEstadoImplemento',
            fields=[
                ('id_estado_implemento', models.AutoField(primary_key=True, serialize=False)),
                ('estado_implemento', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_estado_implemento',
            },
        ),
        migrations.CreateModel(
            name='TblEstadoMantenimiento',
            fields=[
                ('id_estado_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('estado_mantenimiento', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_estado_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TblEstadosServicio',
            fields=[
                ('id_estado_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('estado_servicio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_estados_servicio',
            },
        ),
        migrations.CreateModel(
            name='TblImplemento',
            fields=[
                ('id_ficha_tecnica_implemento', models.AutoField(primary_key=True, serialize=False)),
                ('marca_implemento', models.CharField(max_length=45)),
                ('modelo_implemento', models.CharField(max_length=45)),
                ('referencia_implemento', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad_memoria', models.CharField(blank=True, max_length=45, null=True)),
                ('procesador', models.CharField(blank=True, max_length=45, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=45, null=True)),
                ('perifericos', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_estado_implemento', models.ForeignKey(db_column='id_estado_implemento', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblestadoimplemento')),
            ],
            options={
                'db_table': 'tbl_implemento',
            },
        ),
        migrations.CreateModel(
            name='TblInventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('serial_implemento', models.CharField(max_length=45, unique=True)),
                ('descripcion_implemento', models.TextField()),
                ('id_ficha_tecnica', models.ForeignKey(db_column='id_ficha_tecnica', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblimplemento')),
            ],
            options={
                'db_table': 'tbl_inventario',
            },
        ),
        migrations.CreateModel(
            name='TblMantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('area_mantenimiento', models.CharField(max_length=45)),
                ('fecha_mantenimiento', models.DateField()),
                ('hora_mantenimiento', models.TimeField()),
                ('id_auxiliar', models.ForeignKey(db_column='id_auxiliar', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblauxiliar')),
                ('id_estado_mantenimiento', models.ForeignKey(db_column='id_estado_mantenimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblestadomantenimiento')),
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblinventario')),
            ],
            options={
                'db_table': 'tbl_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TblPermisosUsuario',
            fields=[
                ('id_permisos_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('permiso', models.TextField()),
                ('url_dashboard', models.TextField()),
            ],
            options={
                'db_table': 'tbl_permisos_usuario',
            },
        ),
        migrations.CreateModel(
            name='TblPosicion',
            fields=[
                ('id_posicion', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_posicion',
            },
        ),
        migrations.CreateModel(
            name='TblPrestamo',
            fields=[
                ('id_inventario_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_en_prestamo', models.IntegerField()),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField()),
                ('id_ficha_tecnica', models.ForeignKey(db_column='id_ficha_tecnica', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblimplemento')),
            ],
            options={
                'db_table': 'tbl_prestamo',
            },
        ),
        migrations.CreateModel(
            name='TblPrioridadMantenimiento',
            fields=[
                ('id_prioridad_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_prioridad_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TblPrioridadServicio',
            fields=[
                ('id_prioridad', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_prioridad_servicio',
            },
        ),
        migrations.CreateModel(
            name='TblServicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateField()),
                ('hora_servicio', models.TimeField()),
                ('descripcion_servicio', models.TextField(blank=True, null=True)),
                ('id_auxiliar', models.ForeignKey(db_column='id_auxiliar', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblauxiliar')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblempleado')),
                ('id_estado_servicio', models.ForeignKey(db_column='id_estado_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblestadosservicio')),
                ('id_prioridad_servicio', models.ForeignKey(db_column='id_prioridad_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblprioridadservicio')),
            ],
            options={
                'db_table': 'tbl_servicio',
            },
        ),
        migrations.CreateModel(
            name='TblTipoImplemento',
            fields=[
                ('id_tipo_implemento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_implemento', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_tipo_implemento',
            },
        ),
        migrations.CreateModel(
            name='TblTipoMantenimiento',
            fields=[
                ('id_tipo_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_tipo_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TblTipoServicio',
            fields=[
                ('id_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_tipo_servicio',
            },
        ),
        migrations.CreateModel(
            name='TblTicketServicio',
            fields=[
                ('id_ticket_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ticket', models.CharField(max_length=45)),
                ('conclusion_servicio', models.TextField()),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblservicio')),
            ],
            options={
                'db_table': 'tbl_ticket_servicio',
            },
        ),
        migrations.CreateModel(
            name='TblTicketMantenimiento',
            fields=[
                ('id_reporte_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('conclusion_mantenimiento', models.TextField(blank=True, null=True)),
                ('id_estado_mantenimiento', models.ForeignKey(db_column='id_estado_mantenimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblestadomantenimiento')),
                ('id_mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblmantenimiento')),
            ],
            options={
                'db_table': 'tbl_ticket_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TblSoporteTecnico',
            fields=[
                ('id_soporte_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('id_ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblticketservicio')),
            ],
            options={
                'db_table': 'tbl_soporte_tecnico',
            },
        ),
        migrations.AddField(
            model_name='tblservicio',
            name='id_tipo_servicio',
            field=models.ForeignKey(db_column='id_tipo_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tbltiposervicio'),
        ),
        migrations.CreateModel(
            name='TblPrestamosTecnologicos',
            fields=[
                ('id_prestamos_tecnologicos', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_requerida', models.IntegerField()),
                ('id_inventario_prestamo', models.ForeignKey(db_column='id_inventario_prestamo', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblprestamo')),
                ('id_ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblticketservicio')),
            ],
            options={
                'db_table': 'tbl_prestamos_tecnologicos',
            },
        ),
        migrations.CreateModel(
            name='TblPerfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, upload_to='users/pictures')),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.tblposicion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_perfil',
            },
        ),
        migrations.AddField(
            model_name='tblmantenimiento',
            name='id_prioridad_mantenimiento',
            field=models.ForeignKey(db_column='id_prioridad_mantenimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tblprioridadmantenimiento'),
        ),
        migrations.AddField(
            model_name='tblmantenimiento',
            name='id_tipo_mantenimiento',
            field=models.ForeignKey(db_column='id_tipo_mantenimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tbltipomantenimiento'),
        ),
        migrations.AddField(
            model_name='tblimplemento',
            name='id_tipo_implemento',
            field=models.ForeignKey(db_column='id_tipo_implemento', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tbltipoimplemento'),
        ),
        migrations.AddField(
            model_name='tblempleado',
            name='id_perfil',
            field=models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to='links.tblperfil'),
        ),
        migrations.CreateModel(
            name='TblCoordinador',
            fields=[
                ('id_coordinador', models.AutoField(primary_key=True, serialize=False)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to='links.tblperfil')),
            ],
            options={
                'db_table': 'tbl_coordinador',
            },
        ),
        migrations.AddField(
            model_name='tblauxiliar',
            name='id_disponibilidad_auxiliar',
            field=models.ForeignKey(db_column='id_disponibilidad_auxiliar', on_delete=django.db.models.deletion.DO_NOTHING, to='links.tbldisponibilidadauxiliar'),
        ),
        migrations.AddField(
            model_name='tblauxiliar',
            name='id_perfil',
            field=models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to='links.tblperfil'),
        ),
    ]
